#!/usr/bin/env bash
# Idempotent per-user setup for the devbox. Runs as `dev` from the entrypoint on
# every container start, and by hand through `./bin/devbox bootstrap`. Every step
# is guarded, so a re-run is a no-op that only reprints the checklist.
set -euo pipefail

log_info() { echo -e "\033[0;34m[INFO]\033[0m  $*"; }
log_success() { echo -e "\033[0;32m[OK]\033[0m    $*"; }
log_warn() { echo -e "\033[1;33m[WARN]\033[0m  $*" >&2; }

readonly HOME_DIR="${HOME:-/home/dev}"
readonly SSH_DIR="${HOME_DIR}/.ssh"
readonly TEMPLATE_DIR='/opt/devbox/home'

export PATH="${HOME_DIR}/.local/libexec/devbox-agent:${HOME_DIR}/.local/bin:${PATH}"

# Manual, human-only follow-ups collected while bootstrapping and printed once at
# the end. Nothing here is ever attempted automatically.
declare -a ACTIONS=()
register_action() { ACTIONS+=("$1"); }

# -- 1. OMP -------------------------------------------------------------------
# Deliberately not in the image: installing it here to ~/.local/bin (the
# installer's default PI_INSTALL_DIR, on the bind mount) keeps `omp update`
# working without an image rebuild. Checked by path, not `command -v`: the
# launcher installed in §12 answers to `omp` on the PATH set above.
if [[ -x "${HOME_DIR}/.local/bin/omp" ]]; then
  log_info "OMP already installed: ${HOME_DIR}/.local/bin/omp"
else
  log_info 'Installing OMP...'
  curl -fsSL https://omp.sh/install.sh | sh
fi

# -- 2. SSH identities: public keys only -------------------------------------
# The devbox generates no keys and holds no private key for GitHub. Manual git
# work as yourself runs over the laptop's forwarded 1Password agent; the public
# keys installed here are what selects the right forwarded key per account
# (IdentitiesOnly + IdentityFile <pub> in ~/.ssh/config) and what git names as
# the signing key. Two files per identity because GitHub registers
# authentication and signing keys separately and each account uses a different
# key for each; signing with the auth key verifies locally and shows Unverified
# on GitHub. Agent sessions never see the forwarded agent: their git goes over
# HTTPS with per-operation tokens (§12).
mkdir -p "${SSH_DIR}"
chmod 700 "${SSH_DIR}"
install_pubkey() {
  local file="$1" var="$2" what="$3"
  if [[ -n "${!var:-}" ]]; then
    printf '%s\n' "${!var}" >"${file}"
    chmod 644 "${file}"
  elif [[ ! -f "${file}" ]]; then
    register_action "Set ${var} in .env to the laptop's ${what} public key, then ./bin/devbox up"
  fi
}
for identity in personal work; do
  key="${SSH_DIR}/id_${identity}"
  upper="$(printf '%s' "${identity}" | tr '[:lower:]' '[:upper:]')"
  # A private key generated by an earlier bootstrap is exactly what this layout
  # removes. Its fingerprint goes into the checklist first, because once the
  # file is gone nothing here can name the GitHub entry to revoke.
  if [[ -f "${key}" ]]; then
    fingerprint="$(ssh-keygen -lf "${key}.pub" 2>/dev/null | cut -d' ' -f2 || printf 'unknown')"
    rm -f "${key}"
    log_warn "Removed the devbox-generated private key ${key}; revoke it on GitHub."
    register_action "Revoke the retired devbox-${identity} key on GitHub (fingerprint ${fingerprint}) - both its Authentication and its Signing entry"
  fi
  install_pubkey "${key}.pub" "GIT_${upper}_PUBKEY" "${identity} authentication"
  install_pubkey "${SSH_DIR}/signing_${identity}.pub" "GIT_${upper}_SIGNINGKEY" "${identity} signing"
done

# -- 3. ~/.ssh/config ---------------------------------------------------------
# Rendered every run: it is generated, not hand-edited.
install -m 600 "${TEMPLATE_DIR}/.ssh/config.tpl" "${SSH_DIR}/config"

# -- 4. known_hosts -----------------------------------------------------------
# Seeded from the authenticated GitHub meta API. Without it the first
# agent-driven `git push` blocks forever on a TOFU prompt.
known_hosts="${SSH_DIR}/known_hosts"
if ! grep -q '^github.com ' "${known_hosts}" 2>/dev/null; then
  log_info 'Seeding GitHub host keys into known_hosts...'
  if github_keys="$(curl -fsSL --max-time 15 https://api.github.com/meta | jq -r '.ssh_keys[]')" &&
    [[ -n "${github_keys}" ]]; then
    {
      [[ -f "${known_hosts}" ]] && cat "${known_hosts}"
      while IFS= read -r github_key; do
        [[ -n "${github_key}" ]] && printf 'github.com %s\n' "${github_key}"
      done <<<"${github_keys}"
    } | sort -u >"${known_hosts}.new"
    mv "${known_hosts}.new" "${known_hosts}"
    chmod 600 "${known_hosts}"
  else
    log_warn 'Could not fetch https://api.github.com/meta; known_hosts left untouched.'
    register_action "Seed GitHub host keys: ssh-keyscan github.com >> ${known_hosts}"
  fi
fi

# -- 5. ~/.gitconfig ---------------------------------------------------------
# Template copy once (aliases, colors, whitespace rules), then always re-apply the
# derived values, so regenerated identity settings never fight hand edits.
gitconfig="${HOME_DIR}/.gitconfig"
if [[ ! -f "${gitconfig}" ]]; then
  log_info 'Installing ~/.gitconfig from the template...'
  install -m 644 "${TEMPLATE_DIR}/.gitconfig" "${gitconfig}"
fi

git config --global user.name "${GIT_PERSONAL_NAME:-}"
git config --global user.email "${GIT_PERSONAL_EMAIL:-}"
# Your own commits in a pane sign with the laptop key behind the forwarded
# 1Password agent: ssh-keygen -Y sign takes a public key file and signs through
# SSH_AUTH_SOCK when no private key is on disk. Without a forwarded agent a
# manual commit fails to sign, which is the intended shape of the escape hatch.
git config --global user.signingkey "${SSH_DIR}/signing_personal.pub"
git config --global gpg.format ssh
git config --global commit.gpgsign true
git config --global tag.gpgsign true
git config --global gpg.ssh.allowedSignersFile "${SSH_DIR}/allowed_signers"
git config --global init.defaultBranch main
git config --global pull.rebase true
git config --global pull.ff only
git config --global push.default simple
git config --global push.followTags true
# shellcheck disable=SC2088 # git expands `~` in include paths itself
git config --global includeIf.'gitdir:~/projects/work/'.path '~/.config/work/.gitconfig'

# -- 6. work identity ------------------------------------------------------
mkdir -p "${HOME_DIR}/.config/work"
work_gitconfig="${HOME_DIR}/.config/work/.gitconfig"
git config --file "${work_gitconfig}" user.name "${GIT_WORK_NAME:-}"
git config --file "${work_gitconfig}" user.email "${GIT_WORK_EMAIL:-}"
git config --file "${work_gitconfig}" user.signingkey "${SSH_DIR}/signing_work.pub"
# Rewrites existing `git@github.com:` remotes inside ~/projects/work/ onto the
# work key. New clones must use the alias directly
# (`git clone git@work.github.com:<org>/<repo> ~/projects/work/<repo>`), because
# URL rewriting from an includeIf file cannot apply before the repo directory exists.
git config --file "${work_gitconfig}" url.'git@work.github.com:'.insteadOf 'git@github.com:'
# Boxes bootstrapped before the alias was renamed carry a second rewrite for the
# same URL; leaving both in place makes the chosen remote ambiguous.
git config --file "${work_gitconfig}" --unset-all url.'github-work:'.insteadOf 2>/dev/null || true
git config --file "${work_gitconfig}" --remove-section url.'github-work:' 2>/dev/null || true
while IFS= read -r stale_remote; do
  register_action "Repoint the stale github-work: remote in ${stale_remote%/.git/config}: git -C ${stale_remote%/.git/config} remote set-url origin git@work.github.com:<org>/<repo>"
done < <(grep -ls 'github-work:' "${HOME_DIR}/projects/work"/*/.git/config 2>/dev/null || true)

# -- 7. allowed_signers -------------------------------------------------------
# So `git log --show-signature` verifies your own commits locally; agent commits
# are unsigned by design (§12).
{
  for identity in personal work; do
    var="GIT_$(printf '%s' "${identity}" | tr '[:lower:]' '[:upper:]')_EMAIL"
    [[ -f "${SSH_DIR}/signing_${identity}.pub" ]] && printf '%s %s\n' "${!var:-}" "$(cut -d' ' -f1,2 "${SSH_DIR}/signing_${identity}.pub")"
  done
} >"${SSH_DIR}/allowed_signers"
chmod 644 "${SSH_DIR}/allowed_signers"

# -- 8. work-app GitHub App credentials ---------------------------------
# Secrets: bootstrap creates the directory and never fetches the contents. The
# credential helper (§12) mints a repository-scoped installation token from them
# for every git operation on a repository the App is installed on.
creds_dir="${HOME_DIR}/.config/work/work-app"
mkdir -p "${creds_dir}"
chmod 700 "${creds_dir}"
if [[ ! -f "${creds_dir}/app.pem" ]]; then
  register_action "Place the work-app app credentials: printf '%s' '<app-id>' > ${creds_dir}/app-id, copy the private key to ${creds_dir}/app.pem from the laptop, then chmod 600 ${creds_dir}/app.pem - until then agents push work repositories with the PAT"
fi

# -- 9. Shell -----------------------------------------------------------------
install -d -m 755 "${HOME_DIR}/.bashrc.d"
install -m 644 "${TEMPLATE_DIR}/.bashrc.d/devbox.sh" "${HOME_DIR}/.bashrc.d/devbox.sh"

# The bind mount shadows the image's /home/dev, so a fresh data directory has no
# dotfiles at all - and without ~/.profile a login shell (herdr panes,
# `./bin/devbox shell`) never sources ~/.bashrc. Seed the distro skeleton;
# `cp -n` never touches a file the user already has.
cp -n /etc/skel/.bashrc /etc/skel/.profile /etc/skel/.bash_logout "${HOME_DIR}/" 2>/dev/null || true

bashrc="${HOME_DIR}/.bashrc"
touch "${bashrc}"
if ! grep -q '.bashrc.d' "${bashrc}"; then
  log_info 'Registering ~/.bashrc.d/*.sh in ~/.bashrc...'
  # Prepended, not appended: Ubuntu's skeleton ~/.bashrc returns early for
  # non-interactive shells, and `ssh devbox <cmd>` (how agents and tooling call
  # in) is exactly that. devbox.sh guards its own interactive-only parts.
  loader="$(mktemp)"
  cat >"${loader}" <<'BASHRC'
# -- devbox -------------------------------------------------------------------
for devbox_rc in "$HOME"/.bashrc.d/*.sh; do
  [ -r "$devbox_rc" ] && . "$devbox_rc"
done
unset devbox_rc

BASHRC
  cat "${bashrc}" >>"${loader}"
  mv "${loader}" "${bashrc}"
  chmod 644 "${bashrc}"
fi

if ! grep -q worktrunk "${bashrc}"; then
  log_info 'Installing the worktrunk shell integration...'
  # `wt config shell install` has no --yes flag and reads a confirmation from
  # stdin, which is closed here; feed it one.
  printf 'y\n' | wt config shell install bash || log_warn 'wt config shell install failed; run it by hand.'
fi

# -- 10. Tool credentials -----------------------------------------------------
# One box-wide file of plain KEY=value pairs, sourced by every shell (see
# home/.bashrc.d/devbox.sh) so `ssh devbox <cmd>` sees the same environment a
# pane does. Deliberately not 1Password-backed: the container holds no vault
# access, so values are written here by hand or rendered on the laptop and
# copied in. Per-project secrets belong in the project's own .env, never here.
secrets_dir="${HOME_DIR}/.config/devbox"
mkdir -p "${secrets_dir}"
chmod 700 "${secrets_dir}"
secrets_file="${secrets_dir}/secrets.env"
if [[ ! -f "${secrets_file}" ]]; then
  install -m 600 "${TEMPLATE_DIR}/.config/devbox/secrets.env.example" "${secrets_file}"
  register_action "Fill ${secrets_file} with GH_TOKEN_PERSONAL, GH_TOKEN_WORK and any model API keys, then reconnect."
fi
# A credential file that became group- or world-readable is worth fixing
# silently; it is on the bind mount and survives every rebuild.
chmod 600 "${secrets_file}"

# Leftovers from the op-era layout. /home/dev outlives every rebuild, so a file
# written when `op run` resolved these references is still here - and this file
# is now sourced directly, which would export the literal `op://...` string into
# every shell. Warn instead of editing someone's credential file.
#
# Assignments only: the shipped template mentions `op://` in a comment, so a
# bare `grep op://` would flag every fresh install.
if grep -qE '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=.*op://' "${secrets_file}" 2>/dev/null; then
  log_warn "${secrets_file} still holds op:// references; they are now exported verbatim."
  register_action "Replace the op:// references in ${secrets_file} with plain values (op is no longer installed; render them on the laptop)"
fi
if [[ -f "${secrets_dir}/secrets.work.env" ]]; then
  register_action "Delete the orphaned ${secrets_dir}/secrets.work.env (the per-account op files are gone; one secrets.env now serves every project)"
fi

# -- 11. gh -------------------------------------------------------------------
# One fine-grained token per GitHub account, chosen from the working directory
# by the same rule git uses for identities (~/projects/work/** is work).
# The `gh` shim resolves it per invocation, because an agent's cwd is a project
# while the shell that started it was opened in $HOME - a GH_TOKEN exported at
# startup would pin one account for the whole session. The shim lives in the
# agent directory (§12), which devbox.sh puts first on every PATH here.
#
# `gh auth login` is deliberately not part of this: its web flow can only ask
# for `repo` + `read:org` + `gist` (the floor is hard-coded upstream; `--scopes`
# only adds), i.e. non-expiring read/write on every repo either account can
# reach, stored in plaintext because the container has no keyring.
install -d -m 755 "${HOME_DIR}/.local/bin"
install -m 755 "${TEMPLATE_DIR}/.local/bin/devbox-gh-token" "${HOME_DIR}/.local/bin/devbox-gh-token"
rm -f "${HOME_DIR}/.local/bin/gh" # pre-§12 location of the shim
agent_dir="${HOME_DIR}/.local/libexec/devbox-agent"
install -d -m 755 "${agent_dir}"
install -m 755 "${TEMPLATE_DIR}/.local/libexec/devbox-agent/gh" "${agent_dir}/gh"

# Every `gh` here goes through that shim: the agent directory is first on the
# PATH exported at the top of this script. stderr is dropped because the shim
# reports an unconfigured account on every call, and the checklist below says
# the same thing once, in the place people actually read.
gh config set git_protocol ssh 2>/dev/null

# A plain GH_TOKEN= line still works - the resolver returns it for every
# directory - but it overrides both per-account variables, so nothing is ever
# chosen per tree. Grep the file rather than the environment: this is advice
# about secrets.env, not about whatever the caller happens to export.
if grep -qE '^[[:space:]]*GH_TOKEN=' "${secrets_file}" 2>/dev/null; then
  log_warn "${secrets_file} sets a box-wide GH_TOKEN; it overrides the per-account tokens."
  register_action "Split the box-wide GH_TOKEN in ${secrets_file} into GH_TOKEN_PERSONAL and GH_TOKEN_WORK (as written, the per-directory choice never applies)"
fi

# One entry per account: the directory that selects it, which is the only input
# the resolver takes. Adding an account means adding a line here and a branch in
# home/.local/bin/devbox-gh-token - the same two places docs/secrets.md names.
for account in "personal:${HOME_DIR}" "work:${HOME_DIR}/projects/work"; do
  name="${account%%:*}"
  # Ask the resolver instead of reading the variables here, so this check
  # exercises the exact path `gh` takes - including secrets.env being read
  # directly - and needs no assumption about bootstrap's own cwd.
  if ! token="$(devbox-gh-token "${account#*:}" 2>/dev/null)" || [[ -z "${token}" ]]; then
    register_action "Add a fine-grained GitHub token for the ${name} account to ${secrets_file} as GH_TOKEN_$(printf '%s' "${name}" | tr '[:lower:]' '[:upper:]') (contents write on the repositories agents push without the App; actions and checks read; issues or pull-requests write only if agents should post)"
  elif ! GH_TOKEN="${token}" timeout 15 gh auth status >/dev/null 2>&1; then
    # Present but rejected - expired, revoked, or GitHub unreachable; a
    # variable-is-set check cannot see any of those. `timeout` because this runs
    # from the entrypoint before `exec sshd`: no check may delay SSH access.
    register_action "The GitHub token for the ${name} account is rejected by gh - check expiry and revocation (or network, if this box just came up) and re-issue it in ${secrets_file}"
  fi
done

# -- 12. Agent git override ---------------------------------------------------
# What makes one clone serve both you and an agent: the `omp` launcher exports
# GIT_CONFIG_GLOBAL=~/.config/devbox/agent.gitconfig (HTTPS rewrites, the
# per-operation credential helper, the bot author, signing off) and a
# GIT_SSH_COMMAND that refuses, for its own process tree only. The directory is
# first on the PATH from devbox.sh so `omp` resolves to the launcher ahead of
# ~/.local/bin/omp. All generated files: reinstalled on every run.
for tool in omp devbox-git-credential devbox-git-no-ssh; do
  install -m 755 "${TEMPLATE_DIR}/.local/libexec/devbox-agent/${tool}" "${agent_dir}/${tool}"
done
for cfg in agent.gitconfig agent-work.gitconfig; do
  install -m 644 "${TEMPLATE_DIR}/.config/devbox/${cfg}" "${secrets_dir}/${cfg}"
done

# -- 13. OMP config -----------------------------------------------------------
omp_config_dir="${HOME_DIR}/.omp/agent"
mkdir -p "${omp_config_dir}"
if [[ ! -f "${omp_config_dir}/config.yml" ]]; then
  log_info 'Seeding ~/.omp/agent/config.yml...'
  install -m 644 "${TEMPLATE_DIR}/.omp/agent/config.yml" "${omp_config_dir}/config.yml"
fi

# -- 14. moshi-hook -----------------------------------------------------------
# Companion daemon for the Moshi phone client: it owns the Unix socket the OMP
# extension posts lifecycle events to, serves the local gateway on
# 127.0.0.1:24543 that the app reaches over its own SSH forward, and holds the
# WebSocket that turns those events into push notifications and approvals.
# Installed here rather than in the image for the same reason as OMP (§1): it
# lands in ~/.local/bin on the bind mount, so `moshi-hook update` works without
# a rebuild. That is also why there is no ARG pin - a pin on a self-updating
# bind-mount tool only records the version of the first install. The daemon is
# started by the entrypoint: there is no systemd in this container, so
# `moshi-hook service install` cannot be used.
#
# Fetched directly instead of `curl … install.sh | sh`: upstream's installer
# *skips* verification when checksums.txt or sha256sum is unavailable and
# installs the download anyway, while this repo verifies wherever upstream
# publishes a checksum. The version comes from upstream's own "latest" pointer
# and is then held fixed for both fetches, so the tarball and the checksum can
# never describe two different releases.
if command -v moshi-hook >/dev/null 2>&1; then
  log_info "moshi-hook already installed: $(command -v moshi-hook)"
else
  log_info 'Installing moshi-hook...'
  case "$(uname -m)" in
  x86_64 | amd64) moshi_arch='x86_64' ;;
  aarch64 | arm64) moshi_arch='arm64' ;;
  *) moshi_arch='' ;;
  esac
  moshi_cdn='https://cdn.getmoshi.app/hook'
  moshi_tmp="$(mktemp -d)"
  if [[ -z "${moshi_arch}" ]]; then
    log_warn "Unsupported architecture $(uname -m); skipping moshi-hook."
  elif ! moshi_version="$(curl -fsSL --max-time 15 "${moshi_cdn}/latest/version.txt" | tr -d '[:space:]')" ||
    [[ -z "${moshi_version}" ]]; then
    log_warn 'Could not resolve the latest moshi-hook version; skipping.'
  else
    moshi_asset="moshi-hook_Linux_${moshi_arch}.tar.gz"
    if curl -fsSL --max-time 180 "${moshi_cdn}/${moshi_version}/${moshi_asset}" -o "${moshi_tmp}/${moshi_asset}" &&
      curl -fsSL --max-time 15 "${moshi_cdn}/${moshi_version}/checksums.txt" -o "${moshi_tmp}/checksums.txt" &&
      (cd "${moshi_tmp}" && grep -F "  ${moshi_asset}" checksums.txt | sha256sum -c -) >/dev/null 2>&1 &&
      tar -xzf "${moshi_tmp}/${moshi_asset}" -C "${moshi_tmp}" moshi-hook; then
      install -m 0755 "${moshi_tmp}/moshi-hook" "${HOME_DIR}/.local/bin/moshi-hook"
      # The installer ships this alias too; `moshi <dir>` and `moshi diff` are
      # documented entry points and neither needs the daemon.
      ln -sf moshi-hook "${HOME_DIR}/.local/bin/moshi"
      log_success "Installed moshi-hook ${moshi_version}."
    else
      log_warn 'moshi-hook download or checksum verification failed; skipping.'
    fi
  fi
  rm -rf "${moshi_tmp}"
fi

if command -v moshi-hook >/dev/null 2>&1; then
  # Idempotent, and the cure for the daemon's "agent hooks missing or stale"
  # warning: the extension is generated by the installer, so it has to be
  # rewritten whenever the binary changes. Scoped to OMP deliberately - it is
  # the agent this box runs, and an unscoped install also writes project-local
  # files for agents that are not installed here.
  moshi-hook install --target omp >/dev/null 2>&1 ||
    log_warn 'moshi-hook install --target omp failed; agent events may be stale.'
  # Captured rather than piped into `grep -q`: status prints ~20 lines, grep
  # exits at the first match, and the resulting SIGPIPE makes the pipeline fail
  # under `set -o pipefail` - so the piped form silently never fires.
  moshi_status="$(moshi-hook status 2>/dev/null || true)"
  if [[ "${moshi_status}" == *unpaired* ]]; then
    register_action "Pair with Moshi: copy the token from Settings -> Hooks in the app, run 'moshi-hook pair --token <token>' in the container, then './bin/devbox hook' on the workstation to restart the daemon (while unpaired it is socket-only: no notifications, no approvals)"
  fi
fi

# -- 15. Summary --------------------------------------------------------------
echo
echo '== devbox identity =========================================================='
for identity in personal work; do
  if [[ -f "${SSH_DIR}/id_${identity}.pub" ]]; then
    printf '%-10s %s\n' "${identity}" "$(cat "${SSH_DIR}/id_${identity}.pub")"
  else
    printf '%-10s %s\n' "${identity}" '(no public key - see the checklist)'
  fi
done
echo
echo 'sshd host key fingerprint:'
ssh-keygen -lf "${SSH_DIR}/host/ssh_host_ed25519_key.pub"

if ((${#ACTIONS[@]} > 0)); then
  echo
  echo '== remaining manual steps =================================================='
  for action in "${ACTIONS[@]}"; do
    echo "  - ${action}"
  done
fi
echo '============================================================================'
log_success 'Bootstrap complete.'
