# Generated by container/bootstrap.sh on every start - edit the template, not this
# file. Absolute paths only: agents run non-interactively and never expand `~`
# through a shell.
#
# No private keys live here. IdentityFile names a *public* key, which with
# IdentitiesOnly makes ssh offer exactly that key from the forwarded 1Password
# agent (`ssh -A devbox`) - otherwise the agent would offer every key it holds
# and GitHub would accept whichever account comes first. Agent sessions never
# reach this file: their git is rewritten to HTTPS (docs/git.md).
Host github.com
  User git
  IdentityFile /home/dev/.ssh/id_personal.pub
  IdentitiesOnly yes

Host work.github.com
  HostName github.com
  User git
  IdentityFile /home/dev/.ssh/id_work.pub
  IdentitiesOnly yes

Host *
  ServerAliveInterval 30
  AddKeysToAgent no
