# Generated by container/bootstrap.sh on every start - edit the template, not this
# file. Absolute paths only: agents run non-interactively and never expand `~`
# through a shell.
Host github.com
  User git
  IdentityFile /home/dev/.ssh/id_personal
  IdentitiesOnly yes

Host work.github.com
  HostName github.com
  User git
  IdentityFile /home/dev/.ssh/id_work
  IdentitiesOnly yes

Host *
  ServerAliveInterval 30
  AddKeysToAgent no
