# Generated by container/bootstrap.sh - edit home/.bashrc.d/devbox.sh in the repo.
# shellcheck shell=bash

# Sourced by every shell, interactive or not: `ssh devbox <cmd>` must see the
# same toolchain a pane does.

# OMP installs in ~/.local/bin so `omp update` works without an image rebuild.
# ~/.local/libexec/devbox-agent goes in front of it: that is where the `omp`
# launcher lives (the agent git override, docs/git.md) and the `gh` shim that
# picks a GitHub token per working directory (docs/secrets.md).
for dir in "$HOME/.local/bin" "$HOME/.local/libexec/devbox-agent"; do
  case ":$PATH:" in
  *":$dir:"*) ;;
  *) export PATH="$dir:$PATH" ;;
  esac
done
unset dir

# Node lives outside the bind-mounted home (the mount would shadow it), so nvm
# and corepack keep their state in /opt. /usr/local/bin holds node/npm/pnpm
# symlinks; nvm itself is only sourced for interactive shells, where switching
# versions is the point.
export NVM_DIR=/opt/nvm
export COREPACK_HOME=/opt/corepack

# NPM_CONFIG_PREFIX is deliberately *not* exported here: nvm refuses to activate
# its default Node when it is set ("nvm is not compatible with the
# NPM_CONFIG_PREFIX environment variable"), and the same applies to `prefix=` in
# ~/.npmrc. Global npm installs that must survive an image rebuild pass the
# prefix per call instead: `npm i -g --prefix "$HOME/.local" <pkg>`, which puts
# the binary in ~/.local/bin - already on the PATH set above.

export EDITOR=nano

# The project Docker daemon: a rootless dockerd owned by the `dev` *host* user,
# reached through the socket directory compose bind-mounts here. Exported for
# non-interactive shells too, so `ssh devbox 'docker compose up -d'` works.
# Container paths equal host paths for /home/dev, so relative bind mounts in a
# project's compose file resolve correctly - see docs/docker.md.
export DOCKER_HOST=unix:///run/devbox/docker.sock

# Interactive-only: prompt, aliases, and the ~100ms nvm shell function.
if [[ $- == *i* ]]; then
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  eval "$(starship init bash)"
  alias lg='lazygit'
fi

# Box-wide tool credentials: plain KEY=value pairs, mode 600, on the bind mount.
# Sourced outside the interactive guard on purpose - agents and tooling arrive
# as `ssh devbox <cmd>`, which is non-interactive, and they need the GitHub
# tokens and model keys just as much as a pane does. `set -a` exports every
# assignment without repeating `export` in the file.
#
# Per-project secrets do NOT belong here: each project keeps its own .env, so a
# leak stays scoped to one project. That includes GOOGLE_APPLICATION_CREDENTIALS
# - projects use different GCP projects, so the ADC path is per-project too.
if [ -r "$HOME/.config/devbox/secrets.env" ]; then
  set -a
  . "$HOME/.config/devbox/secrets.env"
  set +a
fi

# GH_TOKEN is deliberately *not* derived here. The GitHub account belongs to the
# working directory (~/projects/work/** is work, as in git's includeIf),
# and an agent's cwd is a project while the shell that started it was opened in
# $HOME - so a value fixed at shell startup would pin the wrong account for the
# whole session. The `gh` shim in ~/.local/libexec/devbox-agent resolves
# GH_TOKEN_PERSONAL or GH_TOKEN_WORK per invocation instead; anything else
# that needs the token should ask the same resolver: GH_TOKEN=$(devbox-gh-token).
# See docs/secrets.md.
