# Generated by container/bootstrap.sh - edit home/.bashrc.d/devbox.sh in the repo.
# shellcheck shell=bash

# Sourced by every shell, interactive or not: `ssh devbox <cmd>` must see the
# same toolchain a pane does.

# OMP installs here so `omp update` works without an image rebuild.
case ":$PATH:" in
*":$HOME/.local/bin:"*) ;;
*) export PATH="$HOME/.local/bin:$PATH" ;;
esac

# Node lives outside the bind-mounted home (the mount would shadow it), so nvm
# and corepack keep their state in /opt. /usr/local/bin holds node/npm/pnpm
# symlinks; nvm itself is only sourced for interactive shells, where switching
# versions is the point.
export NVM_DIR=/opt/nvm
export COREPACK_HOME=/opt/corepack

# NPM_CONFIG_PREFIX is deliberately *not* exported here: nvm refuses to activate
# its default Node when it is set ("nvm is not compatible with the
# NPM_CONFIG_PREFIX environment variable"), and the same applies to `prefix=` in
# ~/.npmrc. Global npm installs that must survive an image rebuild pass the
# prefix per call instead: `npm i -g --prefix "$HOME/.local" <pkg>`, which puts
# the binary in ~/.local/bin - already on the PATH set above.

export EDITOR=nano

# Interactive-only: prompt, aliases, and the ~100ms nvm shell function.
if [[ $- == *i* ]]; then
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  eval "$(starship init bash)"
  alias lg='lazygit'
fi

# Box-wide tool credentials: plain KEY=value pairs, mode 600, on the bind mount.
# Sourced outside the interactive guard on purpose - agents and tooling arrive
# as `ssh devbox <cmd>`, which is non-interactive, and they need GH_TOKEN and
# model keys just as much as a pane does. `set -a` exports every assignment
# without repeating `export` in the file.
#
# Per-project secrets do NOT belong here: each project keeps its own .env, so a
# leak stays scoped to one project. That includes GOOGLE_APPLICATION_CREDENTIALS
# - projects use different GCP projects, so the ADC path is per-project too.
if [ -r "$HOME/.config/devbox/secrets.env" ]; then
  set -a
  . "$HOME/.config/devbox/secrets.env"
  set +a
fi
